export const STORAGE_KEYS = {
  IS_FIRST_VISIT: "IS_FIRST_VISIT",
  BAKER_PROGRESS: "BAKER_PROGRESS",
  FOCUS_LOGS: "FOCUS_LOGS",
  USER_SETTINGS: "USER_SETTINGS",
} as const;

export type StorageKeyName = keyof typeof STORAGE_KEYS;
